# Generated by Django 4.1 on 2022-08-29 00:45

from django.db import migrations, models
import unicodedata


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lista', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('cod_lista', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mercado', models.CharField(max_length=255)),
                ('rua_mercado', models.CharField(max_length=255)),
                ('bairro_mercado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('categoria_produto', models.CharField(max_length=255)),
                ('peso_produto', models.FloatField(verbose_name=unicodedata.decimal)),
            ],
        ),
    ]
